apiVersion: v1
kind: Service
metadata:
  name: everything-allowed-service
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: everything-allowed-deployment
  type: LoadBalancer
