apiVersion: v1
kind: Service
metadata:
  name: everything-allowed-deployment
spec:
  ports:
  - port: 4444
    targetPort: 4444
  selector:
    app: everything-allowed-deployment
  type: LoadBalancer
